---

- block:

  - name: Output our qualfied path
    debug:
      msg: "Processing /{{ environment }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ vars.credentials.name }}"

  - name: Write our string
    include_tasks: create_ssm_entry.yml
    vars:
      key_name: "/{{ environment }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"
      key_type: "{{ credentials.ssm_type|default('String') }}"
      password_value: "{{ credentials.value }}"

  when: credentials.type == 'string'

