---

- block:
    - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Generate us a random password length between 32 and 64 chars
      set_fact:
        credentials: "{{ credentials|combine({ 'password_length': 64|random(32) }) }}"
      no_log: true
  when: credentials.password_length is not defined

- block:
    - block:
        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Generate a password for our keypair
          set_fact:
            keypair_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits length=' + credentials.password_length|default(32)| string()) }}"
          no_log: true

        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Remove tmp file
          file:
            path: /tmp/passwordfile
            state: absent
          no_log: true

        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Save our ssh password
          include_tasks: ssm_entry.yml
          vars:
            key_name: "/{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}/ssh_passphrase"
            key_type: "SecureString"
            password_value: "{{ keypair_password }}"
            description: "Auto generated passphrase for /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"
      when: credentials.hasPassword|default(False)

    - block:
        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Generate a password for our keypair
          set_fact:
            keypair_password: ""
          no_log: true
      when: not credentials.hasPassword|default(False)

    - block:
        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Remove our keys if they exist
          file:
            path: "/tmp/id_rsa_{{ credentials.name }}*"
            state: absent
          no_log: true

        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Create our ssh_keypair
          shell: "rm /tmp/id_rsa_*; ssh-keygen -q -b {{ credentials.bits|default(2048) }} -f /tmp/id_rsa_{{ credentials.name }} -N '{{ keypair_password }}' -C 'Managed by Ansible'"
          register: credentials_result
          no_log: true

        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Set key facts
          set_fact:
            private_key: "{{ lookup('file', '/tmp/id_rsa_' + credentials.name ) }}"
            public_key: "{{ lookup('file', '/tmp/id_rsa_' + credentials.name + '.pub') }}"
          no_log: true

        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Remove our keys
          file:
            path: "/tmp/id_rsa_{{ credentials.name }}*"
            state: absent
          no_log: true
      when: not credentials.private_key|default(False)

    - block:
        - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Set our private key fact
          set_fact:
            private_key: "{{ credentials.private_key }}"
          no_log: true

        - block:
            - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Dump our private key to a file
              copy:
                dest: /tmp/pky_dump.key
                content: "{{ credentials.private_key }}"
                mode: 600
              no_log: true

            - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Generate ssh_public_key
              shell: ssh-keygen -y -f /tmp/pky_dump.key > /tmp/pky_dump.pub
              no_log: true

            - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Get our public key conntents
              set_fact:
                public_key: "{{ lookup('file', ' /tmp/pky_dump.pub') }}"
              no_log: true

            - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Remove our keys
              file:
                path: "/tmp/pky_dump*"
                state: absent
              no_log: true
          when: not credentials.public_key|default(False)

        - block:
            - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) set our public key
              set_fact:
                public_key: "{{ credentials.public_key }}"
              no_log: true
          when:  credentials.public_key|default(False)
      when: credentials.private_key|default(False)

    - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Save our ssh private key
      include_tasks: ssm_entry.yml
      vars:
        key_name: "/{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}/ssh_private_key"
        key_type: "SecureString"
        password_value: "{{ private_key }}"
        description: "Auto generated ssh private key for /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"

    - name: (main/_products/_namespaces/_roles/create_ssh_key_entry) Save our ssh public key
      include_tasks: ssm_entry.yml
      vars:
        key_name: "/{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}/ssh_public_key"
        key_type: "String"
        password_value: "{{ public_key }}"
        description: "Auto generated ssh public key for /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"

  when: credentials.type == 'ssh-key'
