---

- name: ensure our key exists, if not we create it
  set_fact:
    create_key: "{{ lookup('aws_ssm', key_name ) }}"
  no_log: true

- name: Create or update secure key/value pair with default kms key (aws/ssm)
  aws_ssm_parameter_store:
    name: "{{ key_name }}"
    description: "{{ description|default('') }}"
    string_type: "{{ key_type }}"
    value: "{{ password_value }}"
  no_log: true
  when: credentials.overwrite|default(False) or create_key|default('') == ''