---

- block:
    - block:
        - name: Create a password
          set_fact:
            password_value: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation length=' + password_length|default(32)| string()) }}"
        - name: Remove tmp file
          file:
            path: /tmp/passwordfile
            state: absent
      when: not credentials.value|default(False)

    - block:
        - name: Populate a password
          set_fact:
            password_value: "{{ credentials.value }}"
      when: credentials.value|default(False)
  when: credentials.type == 'password'