---

- block:
    - name: (main/_products/_namespaces/_roles/create_password) Generate us a random password length between 32 and 64 chars
      set_fact:
        credentials: "{{ credentials|combine({ 'password_length': 64|random(32) }) }}"
      no_log: true
  when: credentials.password_length is not defined

- block:
    - name: (main/_products/_namespaces/_roles/create_password) Output our qualfied path
      debug:
        msg: "Processing /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ vars.credentials.name }}"

    - block:
        - name: (main/_products/_namespaces/_roles/create_password) Create a password when none is specified
          set_fact:
            this_password_value: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits length=' + credentials.password_length|default(32)| string()) }}"
          no_log: true

        - name: (main/_products/_namespaces/_roles/create_password) Remove tmp file
          file:
            path: /tmp/passwordfile
            state: absent
          no_log: true
      when: not credentials.value|default(False)

    - block:
        - name: (main/_products/_namespaces/_roles/create_password) Populate a password when one is specified
          set_fact:
            this_password_value: "{{ credentials.value }}"
          no_log: true
      when: credentials.value|default(False)

    - name: (main/_products/_namespaces/_roles/create_password) Write our password
      include_tasks: ssm_entry.yml
      vars:
        key_name: "/{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"
        key_type: "SecureString"
        password_value: "{{ this_password_value }}"
        description: "Password for /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"

  when: credentials.type == 'password'
