---

- block:

  - name: Output our qualfied path
    debug:
      msg: "Processing /{{ target }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ vars.credentials.name }}"

  ##sns magic goes here

  when: credentials.type == 'string'

