---

- block:

  - name: Output our qualfied path
    debug:
      msg: "Processing /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ vars.credentials.name }}"

  - name: Write our string
    include_tasks: ssm_entry.yml
    vars:
      key_name: "/{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"
      key_type: "{{ credentials.ssm_type|default('String') }}"
      password_value: "{{ credentials.value }}"
      description: "{{ credentials.ssm_type|default('String') }} entry for  /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/{{ credentials.name }}"
  when: credentials.type == 'string'

