---
- name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) Debug our credentials
  debug:
    msg: "credentials {{ credentials }}"
    verbosity: 1

- block:
    - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) Extract ssm value
      set_fact:
        extract_value: "{{ lookup('aws_ssm', key_name ) }}"
      no_log: true

    - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) Display key and value
      debug:
        msg: "{{ extract_value }} "
        verbosity: 2

    - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) add new key / value pairs to dict
      set_fact:
        secrets: "{{ secrets | combine({item.key: item.value}) }}"
      with_items:
        - { key: '{{ key_name }}', value: '{{ extract_value }}' }
      no_log: true

  when:
    - not credentials.is_delegated|default(False)


- block:
    - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) Assume our child role
      sts_assume_role:
        role_arn: "arn:aws:iam::{{ credentials.account_id }}:role/{{ credentials.role_name }}"
        role_session_name: "{{ 9999999999999999999999 | random | to_uuid }}"
      register: assumed_role
      no_log: true

    - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) Extract ssm value
      raw: "AWS_DEFAULT_REGION={{ ansible_env.AWS_DEFAULT_REGION|default('eu-west-2') }}  AWS_REGION={{ ansible_env.AWS_REGION|default('eu-west-2') }} AWS_SESSION_TOKEN='{{ assumed_role.sts_creds.session_token }}' AWS_ACCESS_KEY_ID='{{ assumed_role.sts_creds.access_key }}' AWS_SECRET_ACCESS_KEY='{{ assumed_role.sts_creds.secret_key }}' aws ssm get-parameter --name '{{ key_name }}' --with-decryption --query 'Parameter.Value' --output 'text'"
      register: extract_value
      ignore_errors: True
      no_log: True

    - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) Display key and value
      debug:
        msg: "{{ key_name }} -- {{ extract_value.stdout | trim }}"
        verbosity: 2

    - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry/extract_ssm_entry) add new key / value pairs to dict
      set_fact:
        secrets: "{{ secrets | combine({item.key: item.value}) }}"
      with_items:
        - { key: '{{ key_name }}', value: '{{ extract_value.stdout | trim }}' }
      no_log: true

  when:
    - credentials.is_delegated|default(False)
    - credentials.account_id|default(False)
    - credentials.role_name|default(False)
