---

- block:

  - name: (main) Create our namespaces
    include: process_products.yml
    loop_control:
      loop_var: product
      index_var: product_index
    vars:
      - product_name: "{{ item.name }}"
    with_items: "{{ products }}"

- block:
    - name: (main/process_products) Display secrets
      debug:
        msg: "secrets \n{{ secrets|pprint }}"
        verbosity: 1
    - name: (main/process_products) Give time to read secrets
      pause:
        prompt: "(main/process_products)  press any key to continue"
    - name: (main/process_products) Give time to read secrets
      copy:
         content: "{{ secrets | to_nice_json }}"
         dest: "/tmp/secrets_{{ansible_date_time.iso8601}}.txt"
      delegate_to: localhost
      when: extract_to_file|default(false)|bool == true
  when: extract_ssm_entry|default(false)|bool == true
