---

- block:

    - name: "Create our namespaces"
      include: process_products.yml
      loop_control:
        loop_var: product
        index_var: product_index
      vars:
        - product_name: "{{ item.name }}"
      with_items: "{{ products }}"
