---

- name: Output our namespace
  debug:
    msg: "Processing /{{ environment }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/*"

- name: Create our role targets
  include: process_roles.yml
  loop_control:
    loop_var: roles
    index_var: role_counter
  with_items: "{{ namespaces.roles }}"