---

- name: (main/process_products) Output our product
  debug:
    msg: "Processing /{{ environment_name }}/{{ account }}/{{ product.name }}/*"

- name: (main/process_products) process our namespace targets
  include: process_namespaces.yml
  loop_control:
    loop_var: namespaces
    index_var: namespace_index
  with_items: "{{ product.namespaces }}"