---

- name: Output our product
  debug:
    msg: "Processing /{{ environment }}/{{ account }}/{{ product.name }}/*"

- name: process our namespace targets
  include: process_namespaces.yml
  loop_control:
    loop_var: namespaces
    index_var: namespace_index
  with_items: "{{ product.namespaces }}"