---

- name: Create string entry
  include: create_string_entry.yml
  loop_control:
    loop_var: credentials
  with_items: "{{ roles.creds }}"

- name: Create password entry
  include: create_password.yml
  loop_control:
    loop_var: credentials
  with_items: "{{ roles.creds }}"