---

- name: (main/process_products/process_namespaces) Output our namespace
  debug:
    msg: "Processing /{{ environment_name }}/{{ account }}/{{ vars.product.name }}/{{ vars.namespaces.name }}/*"

- name: (main/process_products/process_namespaces) Create our role targets
  include: process_roles.yml
  loop_control:
    loop_var: roles
    index_var: role_counter
  with_items: "{{ namespaces.roles }}"