---

- name: (main/process_products/process_namespaces/process_roles) Create string entry
  include: create_string_entry.yml
  loop_control:
    loop_var: credentials
  with_items: "{{ roles.creds }}"
  no_log: true

- name: (main/process_products/process_namespaces/process_roles) Create password entry
  include: create_password.yml
  loop_control:
    loop_var: credentials
  with_items: "{{ roles.creds }}"
  no_log: true

- name: (main/process_products/process_namespaces/process_roles) Create ssh-key entry
  include: create_ssh_key_entry.yml
  loop_control:
    loop_var: credentials
  with_items: "{{ roles.creds }}"
  no_log: true
