---

- block:
  - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry) Create secrets dictionary
    set_fact:
      secrets: {}
    when: secrets is undefined
  - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry) extract_ssm_entry our ssm_entry
    include_tasks: extract_ssm_entry.yml
  when: extract_ssm_entry|default(false)|bool == true


- block:
  - name: (main/_products/_namespaces/_roles/create|string|password|ssh|_entry) Write our ssm_entry
    include_tasks: create_ssm_entry.yml
  when: extract_ssm_entry|default(false)|bool == false
