---

- block:
  - name: Create secrets dictionary
    set_fact:
      secrets: {}
    when: secrets is undefined
  - name: extract_ssm_entry our ssm_entry
    include_tasks: extract_ssm_entry.yml
  when: extract_ssm_entry is defined and extract_ssm_entry == True


- block:
  - name: Write our ssm_entry
    include_tasks: create_ssm_entry.yml
  when: extract_ssm_entry is not defined or extract_ssm_entry == False
